display_name="ULT MINUS"
description="""
Heavily inspired by the mod Brawl Minus...
Introducing ULT MINUS

The smash overhaul mod where every character is only buffed to be more broken than their vanilla iteration! ULT MINUS is a fun casual competitive mod that changes many characters and in the future, many different aspects of the game itself.

This is a full modpack with changes to the SSS, game music, and characters. There are future skins, stage changes, UI changes, and much more planned.

Current Version: Alpha 0.2.1
"""
authors = "leiadog, Jmuze, OpZ"
category = "Param"